### PR TITLE
Only show the WikiProject search field when required

### PR DESCRIPTION
**Pull request by samwilson**
This change hides the WikiProject search field if there
are no WikiProjects in the database for the Wikipedia language
in use.

Half of T152173 is fixed as well, because it's easier to test
this new functionality against a language (pt) that doesn't
have WikiProjects.

Composer is also updated, just for fun.

Bug: https://phabricator.wikimedia.org/T152134
Bug: https://phabricator.wikimedia.org/T152173

### CODE REVIEW

**Comment by kaldari** [comment]
We should also hide the WikiProjects column in the results.

**Comment by kaldari** [comment]
+1. This looks good to me. @MusikAnimal: Can you do a quick test of this version?

**Comment by MusikAnimal** [comment]
It works but visually the column for WikiProjects is still there, it's just left blank. I know this is tricky to do but it'd be nice if we could hide it altogether so the content stretches across the full width of the screen, but what we have now is acceptable.

screen shot 2016-12-05 at 1 35 26 pm

**Comment by kaldari** [comment]
Yeah, that's a bit awkward. Agree it would be better to remove it completely.

**Comment by samwilson** [comment]
Good point. I was attempting to not make the code more complicated, but it does look odd. I've now stretched the 'Page', 'Editor', and 'Review' columns by one extra col each.

**Comment by MusikAnimal** [comment]
Looks good! :+1: from me. That totals +2 and I think we're pretending GitHub is Gerrit so I have also merged

**Pull request merged**
