### PR TITLE
Add option to search reviews by user

### PR DESCRIPTION
**Pull request by ChlodAlejandro**
**Note:** CI builds currently failing due to [T331220](https://phabricator.wikimedia.org/T331220).

This aims to fulfill a requested feature to search through reviews done by someone else.

* Searching by "reviewed cases" now shows a box for filtering by reviewer.
* The `filterUser` parameter can now be used to filter users.
* The leaderboard now includes a link to the user's reviews.
* Added an i18n message and its respective `qqq` entry.
* Converted the search area to CSS grid to make the new input look good.

Bug: [T331219](https://phabricator.wikimedia.org/T331219)

### CODE REVIEW

**Comment by MusikAnimal** [comment]
Apologies for taking so long to get to this!

As you may have noticed, there aren't good instructions for running this locally. I usually test with the native PHP server, but since it's single-threaded, it can't compile the LESS at run time. So, I tried on Toolforge using our staging server, and low and behold the styles are broken there, too! https://plagiabot.toolforge.org/ (I've since switched it back to master, and the broken styles remain)

I'm afraid we'll need to fix this first. The way we're using LESS is _less_ than ideal (pun intended :). I think the styles are probably simple enough that we can move to basic CSS, or find a different system. At any rate, we need to see this working on staging before it can be deployed. I've filed https://phabricator.wikimedia.org/T332078 and am working on this now :)

**Comment by MusikAnimal** [comment]
#158 should fix the CSS issue as well as bumping to PHP 7.4. Once that's merged, we'll just need a rebase here.

**Comment by ChlodAlejandro** [comment]
@MusikAnimal With regards to having this set up locally, I did get this same issue back when I was trying to get the bot set up. The way I sort-of fixed it was by running everything through a Docker container. On my PC, I only ever keep a single install of PHP on the path, so this definitely saved me a lot of headaches (especially with mismatched versions).

I pushed that effort [here](https://github.com/ChlodAlejandro/CopyPatrol/tree/dockerization) some time ago, but I didn't file a PR for it. Right now, it's less than perfect but if you'd like, I can switch it up to use 7.4 once #158 gets merged, fix up the documentation a bit more, and then make a PR for it as well.

**Review by theresnotime — CHANGES_REQUESTED** [review]
@ChlodAlejandro gentle nudge that this can be rebased now :)

**Comment by MusikAnimal** [comment]
> I pushed that effort [here](https://github.com/ChlodAlejandro/CopyPatrol/tree/dockerization) some time ago, but I didn't file a PR for it. Right now, it's less than perfect but if you'd like, I can switch it up to use 7.4 once #158 gets merged, fix up the documentation a bit more, and then make a PR for it as well.

That sounds great! We'd love to have a Docker container for all of our projects. #158 is now merged, so please feel free to make a PR for the Dockerization as well :) Thank you!!!

**Review by theresnotime — APPROVED** [review]

**Comment by ChlodAlejandro** [comment]
Bit of an oopsie, seems like requesting re-review for requested changes on GitHub removes the previous reviewer.

Docker-izing pull request submitted as #159. Thanks @MusikAnimal @theresnotime for the help!

**Comment by MusikAnimal** [comment]
This looks and works great! It's now running on our staging server, example search: https://plagiabot.toolforge.org/en/?filter=reviewed&searchText=&filterUser=Ferien&searchCriteria=page

My only concern is the input for the username doesn't appear unless you first submit with reviewed cases selected. Maybe we should use JS (or possibly even CSS) to show/hide the input based on if "Reviewed cases" is selected?

**Comment by ChlodAlejandro** [comment]
Been thinking about that for some time as well. I just thought of a possible solution, but it's past midnight and I need some sleep. I'll try to get this done within the next 48 hours!

**Comment by ChlodAlejandro** [comment]
@MusikAnimal I've submitted the related improvements as #163. Please take a look when you find the time. 😃

**Pull request merged**
